name: Publish to VS Marketplace

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get branch for tag
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw##*/}
        echo "BRANCH=$branch" >> $GITHUB_ENV
    - uses: ./.github/workflows/build-and-test
    - name: Publish
      if: success() && ${{ env.BRANCH == 'main' }}
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}